version: '3'
services:
  postgres:
    image: "postgres"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root      
    ports:
      - "5432:5432"
    volumes:
      - ./migration/docker-database-initial.sql:/docker-entrypoint-initdb.d/docker-database-initial.sql   

  redis:
    image: redis:alpine
    container_name: redis_api
    ports: 
      - 6379:6379

volumes:
  pgdata:
    driver: local

networks:
  default:

     